### PR TITLE
Named Expressions: Add support for auto-scoped absolute references

### PR DESCRIPTION
**Pull request by thilgen**
### Context
Currently [Named Expressions](https://hyperformula.handsontable.com/guide/named-expressions.html) require reference formulas to use **absolute cell references**

> _By default, references in named expressions are absolute. Most people use absolute references in spreadsheet software like Excel without even knowing about it. Very few know that references can be relative too. Unfortunately, HyperFormula doesn't support relative references inside named expressions at the moment._

Hyperformula, Excel, and Google Sheets all allow absolute references to be defined like this (includes the sheet-decorator)
```
Sheet1!$A$1
Sheet1!$B$1:$D$2
Sheet1!$2:$2
Sheet1!$B:$B
```
However, Excel and Google Sheets **also** allow for absolute references to be defined **without** a sheet-decorator (and the absolute references will be automatically scoped to the current sheet)
```
$A$1
$B$1:$D$2
$2:$2
$B:$B
```
**This PR provides support for auto-scoping absolute references within a named reference formula to the sheet where the named reference is installed**

### Example Data

```
const engine = HyperFormula.buildFromSheets({
  'Sheet1': [[]],
  'Sheet2': [[]],
})
```

| Expression | Evaluated As |
| :----------  | :----------- |
| `engine.addNamedExpression('foo', '=$B$1', 0)` |   `=Sheet1!$B$1`  | 
| `engine.addNamedExpression('foo', '=CONCATENATE($A$1,".2")', 1)` | `=CONCATENATE(Sheet2!$A$1,".2")`  |
| `engine.addNamedExpression('foo', '=SUM($B$1,$D$1)', 1)` | `=SUM(Sheet2!$B$1,Sheet2!$D$1)`  |
| `engine.addNamedExpression('foo', '=SUM($B$1,Sheet1!$D$1)', 1)` | `=SUM(Sheet2!$B$1,Sheet1!$D$1)`  |
| `engine.addNamedExpression('foo', '=SUM($B$1:$D$2)', 1)` | `=SUM(Sheet2!$B$1:$D$2)`|
| `engine.addNamedExpression('foo', '=SUM($2:$2)', 0)` | `=SUM(Sheet1!$2:$2)`|
| `engine.addNamedExpression('foo', '=SUM($B:$B)', 1)` | `=SUM(Sheet2!$B:$B)`  |

**Note 1: This is my very first code PR for Hyperformula - So I am very open to feedback, suggestions, or corrections.**

**Note 2: Probably a bunch of other tests that could be added?**

### How did you test your changes?
- New unit tests

### Types of changes
- [ ] Breaking change (a fix or a feature because of which an existing functionality doesn't work as expected anymore)
- [X] New feature or improvement (a non-breaking change that adds functionality)
- [ ] Bug fix (a non-breaking change that fixes an issue)
- [ ] Additional language file, or a change to an existing language file (translations)
- [ ] Change to the documentation

### Related issues:
1. Couldn't find anything in Issues...

### Checklist:
- [ ] My change is compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard.
- [X] My change is compatible with Microsoft Excel.
- [X] My change is compatible with Google Sheets.
- [X] My code follows the code style of this project.
- [ ] I described my changes in the [CHANGELOG.md](https://github.com/handsontable/hyperformula/blob/master/CHANGELOG.md) file.
- [X] My changes require a documentation update.
- [ ] My changes require a migration guide.

### CODE REVIEW

**Comment by AMBudnik** [comment]
That's an interesting idea and has a lot of research. Thank you so much for sharing it with us. 
Nowadays it takes us a little bit longer to do the code review but we will definitely do that and notify you about the results.

**Comment by sequba** [comment]
@thilgen Is this feature important for your use-case of HyperFormula?

**Comment by thilgen** [comment]
Some more info from the Hyperformula docs about absolute reference that lack sheet-decorators

https://hyperformula.handsontable.com/guide/cell-references.html#relative-references

image

**Comment by thilgen** [comment]
I am withdrawing this request - https://github.com/handsontable/hyperformula/issues/1206#issuecomment-1483722255

**Pull request closed without merging**
