### PR TITLE
Improve efficiency of the dependency graph (56% speed-up)

### LINKED ISSUE #876: Slow graph building with 500k of rows without formulas
hi，
we use handsonetable + hyperformula to develop sheet like excel. But we find when setSheetContent or buildfromsheets with huge datas may has bad performance.

demo:
setSheetContent 50w rows data (do not has any formula) will cost 50s
https://jsfiddle.net/rdfa45vp/21/

but spreadjs just cost 2~3s

### PR DESCRIPTION
**Pull request by sequba**
### Test case

A spreadsheet with 500k rows and 10 columns filled with string data. Total of 5M data cells, no formulas.

Script:
```ts
const hf = HyperFormula.buildFromArray([], {
  licenseKey: 'gpl-v3',
  maxRows: 500100,
  useStats: true,
  chooseAddressMappingPolicy: new AlwaysDense(),
})

const data = Array(500000).fill(0).map(() => Array(10).fill(0).map(() => 'A500000'))

var ty1 = (new Date()).getTime()
hf.setSheetContent(0, data)
var ty2 = (new Date()).getTime()
console.log(ty2 - ty1)
console.log(hf.getStats())
```

#### Ideas for improvement

- Function `getTopSortedWithSccSubgraphFrom`, which is the iterative implementation of the Tarjan algorithm that performs the topological sorting of the dependency graph and finds cycles (SCCs) in the graph. In this test case, the dependency graph is trivial; it contains only isolated nodes without any edges. It seems that it can be done more efficiently.
- Function `parseDateTimeFromConfigFormats`, which tries to parse all string data as date/time values. This test case contains no date/time values, so there might be some way of saving time by determining it quickly and avoiding running the heavy parsing operations.

### This PR focuses on optimizing topological sorting of the dependency graph

I made the Tarjan algorithm more efficient by changing the data structures it uses. Initially, the information about the graph nodes was stored in maps and sets with nodes as keys:

```ts
    const entranceTime: Map<T, number> = new Map()
    const low: Map<T, number> = new Map()
    const parent: Map<T, T> = new Map()
    const inSCC: Set<T> = new Set()
```
 
My approach was to use simple arrays indexed by integer ids and keep a single array of nodes as a mapping from id to node data.

```ts
  private nodes: T[] = []

  private entranceTime: number[] = []
  private low: number[] = []
  private parent: number[] = []
  private inSCC: boolean[] = []
```

### Results

Total time:
Before: **25923ms**
After: **11160ms**

Function `getTopSortedWithSccSubgraphFrom`:
Before: **51.6%**
After: **23.1%**

Profiler:
Before:
image

After:
image

Profiler: Chrome Dev Tools

### How did you test your changes?

- unit tests passed
- new unit tests for the Graph class

Comparison on our existing performance benchmarks on my PC:
```
                                     testName | before |  after
-----------------------------------------------------------------------
                                      Sheet A | 417.77 | 401.12
                                      Sheet B | 133.09 | 129.18
                                      Sheet T | 119.23 | 114.51
                                Column ranges | 292.47 | 408.56   <-- 40% slow-down
Sheet A:  change value, add/remove row/column |     23 |   27.2
 Sheet B: change value, add/remove row/column |    169 |  194.0
                   Column ranges - add column |  136.8 |  137.4
                Column ranges - without batch |  339.2 |  316.8
                        Column ranges - batch |    124 |   80.0
```

#### Column ranges benchmark

The 40% slow-down is observed only in Node environment. Running this benchmark in V8 yields similar results before and after applying the change.

### Types of changes

- [ ] Breaking change (a fix or a feature because of which an existing functionality doesn't work as expected anymore)
- [x] New feature or improvement (a non-breaking change that adds functionality)
- [ ] Bug fix (a non-breaking change that fixes an issue)
- [ ] Additional language file, or a change to an existing language file (translations)
- [ ] Change to the documentation

### Related issues:
Fixes #876

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to HyperFormula](https://hyperformula.handsontable.com/guide/contributing.html) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://goo.gl/forms/yuutGuN0RjsikVpM2).
- [x] My change is compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard.
- [x] My change is compatible with Microsoft Excel.
- [x] My change is compatible with Google Sheets.
- [x] I described my changes in the [CHANGELOG.md](https://github.com/handsontable/hyperformula/blob/master/CHANGELOG.md) file.
- [ ] My changes require a documentation update.
- [ ] My changes require a migration guide.

### CODE REVIEW

**Comment by sequba** [comment]
TODO:
- calculate the performance gain
- check other scenarios if we have no slow-downs (cruds?)
- try out other ideas from TODOs in the code

**Review by budnix — APPROVED** [review]
Looks great! 🥇 

I tested the changes using the demo provided in the PR's description, and here are my results:
 * On Chrome (browser), there is a 60% improvement (from ~25s to ~10s);
 * Node (v20), there is a 58% improvement (from ~29s to ~12s);

**Comment by sequba** [comment]
@budnix Could you also run the `Column ranges` benchmark yourself? I'm curios if you'd confirm my results. Here's the code:

```js
import { AlwaysDense, HyperFormula } from 'hyperformula';

function columnIndexToLabel(column) {
  let result = ''

  while (column >= 0) {
    result = String.fromCharCode((column % 26) + 97) + result
    column = Math.floor(column / 26) - 1
  }

  return result.toUpperCase()
}

function simpleCellAddressToString(address) {
  const column = columnIndexToLabel(address.col)
  return `${column}${address.row + 1}`
}

const cols = 50;
const data = [];
const firstRow = [1];

for (let i = 1; i < cols; ++i) {
  const adr = simpleCellAddressToString({sheet: 0, row: 0, col: i - 1});
  firstRow.push(`=${adr} + 1`);
}

data.push(firstRow);

for (let i = 1; i < cols; ++i) {
  const rowToPush = Array(i).fill(null);
  const startColumn = columnIndexToLabel(i - 1);

  for (let j = i - 1; j < cols - 1; ++j) {
    const endColumn = columnIndexToLabel(j);
    rowToPush.push(`=SUM(${startColumn}:${endColumn})`);
  }

  data.push(rowToPush);
}

const sheetId = 0;
const ty1 = (new Date()).getTime();

for (let i = 1; i < 200 ; ++i) {
  const hf = HyperFormula.buildFromArray([], {
    licenseKey: 'gpl-v3',
    maxRows: 500100,
    useStats: true,
    chooseAddressMappingPolicy: new AlwaysDense(),
  });

  hf.setSheetContent(sheetId, data);
}

const ty2 = (new Date()).getTime();
console.log(ty2 - ty1);
```

**Comment by budnix** [comment]
> @budnix Could you also run the `Column ranges` benchmark yourself? I'm curious if you'd confirm my results.

Using your code, the improvement isn't as spectacular as in PR's description. I tested on Node 20. Before PR ~25s after PR ~23s.

**Comment by AMBudnik** [comment]
Released in v2.6.0

**Comment by izulin** [comment]
awesome!

**Pull request merged**
