### PR TITLE
Changed whitespace regex -> /s+.

### PR DESCRIPTION
**Pull request by MartinDawson**
### Context
A crazy bug I just ran into caused by this.

In our spreadsheet we use a contentEditable div. We parse the text using chevrotain's lexer to find the cells to highlight. Like so:

image

When we access the content using `.textContent` it seems to replace all spaces with non-breaking spaces.

This should be fine because hyperformula should replace ANY space. However it's missing non-breaking spaces from the regex: 

`pattern: /[ \t\n\r]+/`

Hyperformula's lexer was returning `#ERROR!` due to this.

So it should be `/s+` instead.

### How has this been tested?
See the spec test.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] I described the modification in the CHANGELOG.md file.

### CODE REVIEW

**Comment by MartinDawson** [comment]
Is their plans to more actively maintain this repository now woj is not doing it? Because we have branches/PR's that are becoming backlogged off each other and maintaining them will be a pain if stuff is not getting merged or feedback given. This is a tiny PR...

If not then I think we will just develop in our own repo instead and not try and keep in sync with this main repo.

**Comment by warpech** [comment]
I am sorry to have disappointed you by not reviewing your PR within a few days. The project is actively maintained within our capacity and roadmap. We will be happy to review this when we come to it.

**Comment by warpech** [comment]
We have assigned a developer to work on accepting your PR and fixing other bugs starting from February.

**Comment by sequba** [comment]
We need to check the compliance with OpenFormula standard.

**Review by sequba — APPROVED** [review]

**Comment by sequba** [comment]
@MartinDawson I want to merge your PR. Could you resolve the conflicts, please?

**Comment by sequba** [comment]
These changes have been merged into `feature/issue-898/resolve-conflicts` and will proceed into develop via second PR: #935

**Comment by AMBudnik** [comment]
Hi @MartinDawson I'm the lucky one to announce that the proposed changes, further developed by @sequba and merged to `develop` via the following PR https://github.com/handsontable/hyperformula/pull/935 are published under Hyperformula v2.0.0 released today. Thank you so much for your feedback and the time to share your thoughts.

Here https://github.com/handsontable/hyperformula/issues/964 is the full list of changes for HyperFormula v2.

**Pull request merged**
