### PR TITLE
Reversed ranges

### PR DESCRIPTION
**Pull request by sequba**
### Context
Parser handles reversed ranges as part of the normalization process.

Simple explanation: Formula `=B2:A1` results in error. After this PR it will be valid and equivalent to `=A1:B2` (in compliance with ODFF standard).

Works for:
- cell ranges
- column ranges
- row ranges
- relative and absolute addressing
- OFFSET addressing for range ends
- sheet references (including ranges that span multiple sheets)

### How has this been tested?
- build works correctly
- unit tests pass
- new unit tests added to verify this feature

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #834 
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [x] My change requires a change to the documentation,
- [x] I described the modification in the CHANGELOG.md file.

### CODE REVIEW

**Comment by sequba** [comment]
@warpech @kirszenbaum I wanted to describe this behaviour in the docs but we do not have a guide about ranges. Do you think we need it?

**Comment by sequba** [comment]
Duplicate PR

**Comment by sequba** [comment]
Closed by mistake

**Review by warpech — COMMENTED** [review]
I reviewed this PR on a call with @sequba and the code looks good. However, we've agreed that two more tasks will be done in this PR:

- perf measurement by @sequba, comparing this PR to `develop`
- docs by @kirszenbaum

**Review by warpech — APPROVED** [review]
Thank you for the detailed performance check.

**Pull request merged**
