### PR TITLE
[Draft] Added async functionality

### PR DESCRIPTION
**Pull request by MartinDawson**
Checklist for completed PR:

- [x] Tested in a real application
- [ ] Async and non async. We need to convert `runFunctionWithReferenceArgument` to async as well and add tests. Also the argumentTypes needs to allow async as users could want default async parameters. I.e like this:

`{argumentType: ArgumentTypes.ASYNC, defaultValue: '=PRICE("AMZN")'},`

- [x] Parallel evaluation
- [x] Repetitive ASTs - `volatile: true` should handle this automatically. Not async specific.
- [x] Error handling - Added TIMEOUT error & handling normal errors.
- [x] Circular dependencies - Shouldn't matter. It's already handled by existing code unless it's part of parallel evaluation which is mentioned blelow.
- [x] Named Ranges
- [x] Volatile - Users should implement their own cache on backend for requests. If a function is volatile then use `volatile: true`
- [x] Undo-redo - Should re-do the function again like normal. Google Sheets does this. (needs tests)
- [x] API has to be async. Used a Tuple for this.
- [x] Helper functions
- [x] Batch

### Context
Unfinished PR. Draft here for continuous review from handsontable devs

Key points:

- The public functions should not be async by default as we want to return the changes still for the first run through. So I've returned a Tuple with [changes, promise] and internally. This allows users to await the promise if they need to however it's not mandatory as they can also listen for the `AsyncValuesUpdated` (async equivalent to `ValuesUpdated` event) event to be fired and update their cells.

### How has this been tested?
async-functions.spec.ts

### Types of changes
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/hyperformula/issues/9

### Checklist:

- [x] My code follows the code style of this project,
- [x] My change requires a change to the documentation,
- [x] I described the modification in the CHANGELOG.md file.

### CODE REVIEW

**Comment by MartinDawson** [comment]
Possible enhancements:

- [ ] Pre-fetch. We could allow users of Hyperformula to fire the async formulas & it's dependencies but not do the calculations on resolve of the promise. This is similar to pre-fetching a links that webpages do when the user hovers over them. For example, the user types `=PRICE("GM")` into a cell but doesn't click enter we could immediately start fetching the async data.

**Comment by MartinDawson** [comment]
Converted `Loading...` to be a cell error instead of normal text. Same as Google Sheets this allows all dependent cells to automatically have the `Loading...` error to which is correct.

**Comment by MartinDawson** [comment]
Parallel evaluation is done.

Just thinking it might be better to split out asyncMethod into a seperate one like the arraySize method. This way we don't need to convert runFunction stuff I think.

Can do that at a later date though.

**Comment by MartinDawson** [comment]
Not correct implementation in the end after testing, so closing.

**Comment by zukilover** [comment]
Hi @MartinDawson , I've noticed that your 2 PRs on async function have been closed. I'm wondering if there is still any ongoing development on this specific feature?

**Comment by warpech** [comment]
@zukilover I replied in https://github.com/handsontable/hyperformula/issues/9#issuecomment-1029829216

**Pull request closed without merging**
