### PR TITLE
feat(function): add MINIFS and MAXIFS

### PR DESCRIPTION
**Pull request by rkretzschmar**
### Context
- adds two not implemented functions `MINIFS` and `MAXIFS` to the built-in functions
- adds only English and German translations, all other language files contain the English translation to pass the `i18n.spec.ts`
- describes the two new functions in the `built-in-functions.md`

### How has this been tested?
- added two new test suites `function-minifs.spec.ts` and `function-maxifs.spec.ts`

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Additional language file or change to the existing one (translations)
- [x] Change to the documentation

### Related issues:
none

### Checklist:

- [x] My code follows the code style of this project.
- [ ] I described the modification in the CHANGELOG.md file.
- [x] My change requires a change to the documentation.
- [ ] My change requires a migration guide.

### CODE REVIEW

**Comment by sequba** [comment]
Hi @rkretzschmar! Thank you very much for your contribution and for signing the Contributor License Agreement. We'll the pull request shortly.

**Comment by sequba** [comment]
@rkretzschmar We will try to fit this into the upcoming release.

**Comment by rkretzschmar** [comment]
> @rkretzschmar We will try to fit this into the upcoming release.

Great, let me know if I can help. I am happy to refactor the whole thing if necessary

**Comment by sequba** [comment]
> Great, let me know if I can help. I am happy with refactoring the whole thing if necessary

@rkretzschmar Thanks a lot. I reviewed the code. You did a great job. I love the tests. I'll take care of all the details myself.

**Comment by sequba** [comment]
> Great, let me know if I can help. I am happy with refactoring the whole thing if necessary

@rkretzschmar Thanks a lot. I reviewed the code. You did a great job. I love the tests. I'll take care of all the details myself.

**Comment by AMBudnik** [comment]
Hi @rkretzschmar I'm just here to share the great news, @sequba just released a new version of HyperFormula with your feature merged

**Pull request merged**
