### PR TITLE
Convert all demos to Stackblitz to prevent the auto-scrolling glitch

### LINKED ISSUE #1412: [Bug]: Docs scrolls automatically to `#demo` on refresh
### Description

Steps to reproduce:
- open https://hyperformula.handsontable.com/guide/named-expressions.html
- make sure there is no `#` in the URL
- click "Refresh" button
Expected: Browser will still display the top of the `Named Expressions` page
Actual: The `#demo` suffix is added to the URL and the page is scrolled automatically to the demo section

Other docs pages are also affected

### Demo

https://hyperformula.handsontable.com/guide/named-expressions.html

### Your environment

Chrome for Windows

### PR DESCRIPTION
**Pull request by sequba**
### Context

After analyzing the issue, I found that it's caused by Codesandbox, which, when embedded in an iframe, calls `Element.scrollIntoView()` or some similar API method to cause the entire page to scroll to the demo.

In my opinion, the best solution is to convert all demos to Stackblitz, which doesn't do that and is, moreover, generally more reliable. @evanSe approved that solution.

Alternative solutions:

1. Temporary position the demo on top of the page and then bring it back to its original position after a delay:

```html
<iframe onload="console.log('absolute'); this.style.position='absolute'; this.style.top='-9999em'; setTimeout(() => { console.log('static'); this.style.position='static'; }, 800);">
```

Work less reliably, delay must be pretty long, if a user scrolls to the demo before the timeout they won't see the iframe.

2. Delay initialization of an iframe until a user scrolls to its vicinity.

```html
<iframe loading="lazy">
```

Auto-scrolling still happens, but only when the user scrolls the guide to a section close to the demo. For short guides (e.g., https://hyperformula.handsontable.com/guide/integration-with-vue.html), lazy-loading will work the same as the default loading.

### How did you test your changes?

Tested locally. Verified that all demos in the guides:
- [x] work correctly in Stackblitz
- [x] are displayed correctly in iframes in the guides
- [x] don't cause the auto-scrolling glitch

### Types of changes

- [ ] Breaking change (a fix or a feature because of which an existing functionality doesn't work as expected anymore)
- [ ] New feature or improvement (a non-breaking change that adds functionality)
- [ ] Bug fix (a non-breaking change that fixes an issue)
- [ ] Additional language file, or a change to an existing language file (translations)
- [x] Change to the documentation

### Related issues:
1. Fixes #1412 

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to HyperFormula](https://hyperformula.handsontable.com/guide/contributing.html) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://goo.gl/forms/yuutGuN0RjsikVpM2).
- [x] My change is compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard.
- [x] My change is compatible with Microsoft Excel.
- [x] My change is compatible with Google Sheets.
- [ ] I described my changes in the [CHANGELOG.md](https://github.com/handsontable/hyperformula/blob/master/CHANGELOG.md) file.
- [ ] My changes require a documentation update.
- [ ] My changes require a migration guide.

### CODE REVIEW

**Comment by evanSe** [comment]
Could you check if this resolves the issue eg `vertical-scroll 'none'` `<iframe src="..." allow="vertical-scroll 'none'"></iframe>`

**Comment by evanSe** [comment]
@magierg could you verify everything is good from a docs perspective, thanks!

**Comment by sequba** [comment]
> Could you check if this resolves the issue eg `vertical-scroll 'none'` `<iframe src="..." allow="vertical-scroll 'none'"></iframe>`

I checked this. It doesn't work

**Comment by sequba** [comment]
@evanSe @magierg it's ready for CR and testing.

**Review by evanSe — APPROVED** [review]

**Comment by magierg** [comment]
this has been verified both locally - all the demos work, but most of them (those build on parcel) have long loading time and throw console errors - fixing it will require updating these demos to newer version of parcel or (even better) to vite -  this has been discussed with @evanSe as well

**Pull request merged**
